onboarding = false
[keys]
prefix = "ctrl+a"
detach = "prefix+d"
split_horizontal = "prefix+s"

[terminal]
default_shell = "/bin/zsh"

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+alt+e"
type = "popup"
command = "lazygit --work-tree \"${HOME}\" --git-dir \"${HOME}\"/.dot"
description = "run lazygit for dotfiles"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+t"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "open scratch terminal"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+y"
type = "popup"
command = "yazi"
description = "open yazi"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+f"
type = "pane"
command = "herdr-sessionizer"

[theme]
name = "gruvbox"
auto_switch = false

[ui.toast]
delivery = "herdr"

[ui]
agent_panel_sort = "spaces"
