bind-key e display-popup -d "#{pane_current_path}" -w 80% -h 80% -E 'yazi'
bind-key g display-popup -d "#{pane_current_path}" -w 80% -h 80% -E 'lazygit'
bind-key C-w display-popup -w 30% -E "$HOME/.local/bin/tmux-session-switcher"
bind-key Z run-shell "$HOME/.local/bin/tmux-popup-toggle '#{session_name}'"

bind-key C-f display-popup -E "$HOME/.local/bin/tmux-sessionizer"

# Run Claude Code in a separate session
bind -r C-c run-shell '\
  SESSION="claude-$(echo #{pane_current_path} | md5sum | cut -c1-8)"; \
  tmux has-session -t "$SESSION" 2>/dev/null || \
  tmux new-session -d -s "$SESSION" -c "#{pane_current_path}" "claude"; \
  tmux display-popup -w80% -h80% -E "tmux attach-session -t $SESSION" || true'

# Run a terminal in a separate session
bind -r C-t run-shell '\
  SESSION="popup-$(echo #S)-$(echo #{pane_current_path} | md5sum | cut -c1-8)"; \
  tmux has-session -t "$SESSION" 2>/dev/null || \
  tmux new-session -d -s "$SESSION" -c "#{pane_current_path}" "zsh"; \
  tmux display-popup -w80% -h80% -E "tmux attach-session -t $SESSION" || true'
