return {
  -- -- file explorer
  -- {
  --   "nvim-neo-tree/neo-tree.nvim",
  --   cmd = "Neotree",
  --   keys = {
  --     { "<space>e", "<cmd>Neotree toggle<cr>",           desc = "Neotree" },
  --     { "<space>c", "<cmd>Neotree reveal_force_cwd<cr>", desc = "Neotree File CWD" },
  --   },
  --   deactivate = function()
  --     vim.cmd([[Neotree close]])
  --   end,
  --   init = function()
  --     vim.g.neo_tree_remove_legacy_commands = 1
  --     if vim.fn.argc() == 1 then
  --       local stat = vim.loop.fs_stat(vim.fn.argv(0))
  --       if stat and stat.type == "directory" then
  --         require("neo-tree")
  --       end
  --     end
  --   end,
  --   opts = {
  --     popup_border_style = "rounded",
  --     filesystem = {
  --       bind_to_cwd = false,
  --       follow_current_file = { enabled = true },
  --       use_libuv_file_watcher = true,
  --     },
  --     window = {
  --       width = 30,
  --       mappings = {
  --         ["<space>"] = "none",
  --       },
  --     },
  --     default_component_configs = {
  --       indent = {
  --         with_expanders = true, -- if nil and file nesting is enabled, will enable expanders
  --         expander_collapsed = "",
  --         expander_expanded = "",
  --         expander_highlight = "NeoTreeExpander",
  --       },
  --       git_status = {
  --         symbols = {
  --           -- Change type
  --           added     = "", -- or "✚", but this is redundant info if you use git_status_colors on the name
  --           modified  = "", -- or "", but this is redundant info if you use git_status_colors on the name
  --           deleted   = "", -- this can only be used in the git_status source
  --           renamed   = "", -- this can only be used in the git_status source
  --           -- Status type
  --           untracked = "",
  --           ignored   = "",
  --           unstaged  = "",
  --           staged    = "",
  --           conflict  = "",
  --         }
  --       },
  --     },
  --     source_selector = {
  --       winbar = true,
  --       statusline = false,
  --       sources = {
  --         { source = "filesystem", display_name = "  Files " },
  --         { source = "buffers", display_name = "  Buffers" },
  --         { source = "git_status", display_name = "  Git " },
  --       },
  --     }
  --   },
  --   config = function(_, opts)
  --     require("neo-tree").setup(opts)
  --     vim.api.nvim_create_autocmd("TermClose", {
  --       pattern = "*lazygit",
  --       callback = function()
  --         if package.loaded["neo-tree.sources.git_status"] then
  --           require("neo-tree.sources.git_status").refresh()
  --         end
  --       end,
  --     })
  --   end,
  -- },
}
