# general
[[mgr.prepend_keymap]]
on   = [ "A" ]
run  = "toggle_all --state=on"
desc = "Toggle all"

[[mgr.prepend_keymap]]
on   = [ "g", "-" ]
run  = "back"
desc = "Go back to previous directory"

# plugin
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

## compress
[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

# bookmark
[[mgr.prepend_keymap]]
on   = [ "g", "m", "d" ]
run  = "cd ~/Documents/"
desc = "Cd to ~/Documents/"

[[mgr.prepend_keymap]]
on   = [ "g", "m", "l" ]
run  = "cd ~/Downloads/"
desc = "Cd to ~/Downloads/"

[[mgr.prepend_keymap]]
on   = [ "g", "m", "g" ]
run  = "cd ~/GitHub/"
desc = "Cd to ~/GitHub/"

[[mgr.prepend_keymap]]
on   = [ "g", "m", "." ]
run  = "cd ~/dotfiles/"
desc = "Cd to ~/dotfiles/"
