spacing         = 2
padding         = 2
hide_ascii      = false
separator       = ""
key_color       = "Cyan"
separator_color = "Blue"
palette         = "Light"

[bar]
glyph           = ""
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = true
