return {
  -- {
  --   "max397574/better-escape.nvim",
  --   config = function()
  --     require("better_escape").setup {
  --       default_mappings = false,
  --       mappings = {
  --         i = {
  --           n = {
  --             n = "<Esc>",
  --           },
  --         },
  --         c = {
  --           n = {
  --             n = "<Esc>",
  --           },
  --         },
  --         t = {
  --         },
  --         v = {
  --           n = {
  --             n = "<Esc>",
  --           },
  --         },
  --         s = {
  --           n = {
  --             n = "<Esc>",
  --           },
  --         },
  --       },
  --     }
  --   end,
  -- },
}
