return {
  --
  {
    'SmiteshP/nvim-navic',
    lazy = true,
    config = function()
      -- vim.api.nvim_set_hl(0, "NavicText", { fg = "Fg", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicSeparator", { fg = "Grey", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsArray", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsBoolean", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsClass", { fg = "Red", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsColor", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsConstant", { fg = "Blue", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsConstructor", { fg = "Green", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsDefault", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsEnum", { fg = "Yellow", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsEnumMember", { fg = "Purple", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsEvent", { fg = "Orange", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsField", { fg = "Green", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsFile", { fg = "Green", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsFolder", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsFunction", { fg = "Green", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsInterface", { fg = "Yellow", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsKey", { fg = "Red", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsKeyword", { fg = "Red", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsMethod", { fg = "Green", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsModule", { fg = "Purple", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsNamespace", { fg = "Purple", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsNull", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsNumber", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsObject", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsOperator", { fg = "Orange", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsPackage", { fg = "Purple", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsProperty", { fg = "Blue", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsReference", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsSnippet", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsString", { fg = "Aqua", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsStruct", { fg = "Yellow", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsText", { fg = "Fg", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsTypeParameter", { fg = "Yellow", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsUnit", { fg = "Purple", bg = "NONE", ctermbg = "NONE" })
      -- vim.api.nvim_set_hl(0, "NavicIconsVariable", { fg = "Blue", bg = "NONE", ctermbg = "NONE" })
      -- require('nvim-navic').setup({ highlight = false })
    end
  },
}
