[tools]
bat = "latest"
"cargo:eza" = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
herdr = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
ripgrep = "latest"
tree-sitter = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
