[tools]
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
herdr = "latest"
lazygit = "latest"
neovim = "0.11.4"
node = "lts"
ripgrep = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
